security:
  oauth2:
    client:
      clientId: myClient
      clientSecret: myClientSecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
    resource.jwt:
      key-pair:
        alias: mytestkey
        store-password: mystorepass
